const countriesData = [
  {
    country: 'Albania',
    alpha2: 'AL',
    alpha3: 'ALB',
    numeric: 8,
    latitude: 41,
    longitude: 20,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/al/1024.png',
  },
  {
    country: 'Andorra',
    alpha2: 'AD',
    alpha3: 'AND',
    numeric: 20,
    latitude: 42.5,
    longitude: 1.6,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/ad/512.png',
  },
  {
    country: 'Austria',
    alpha2: 'AT',
    alpha3: 'AUT',
    numeric: 40,
    latitude: 47.3333,
    longitude: 13.3333,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/at/512.png',
  },
  {
    country: 'Belarus',
    alpha2: 'BY',
    alpha3: 'BLR',
    numeric: 112,
    latitude: 53,
    longitude: 28,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/by/512.png',
  },
  {
    country: 'Belgium',
    alpha2: 'BE',
    alpha3: 'BEL',
    numeric: 56,
    latitude: 50.8333,
    longitude: 4,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/be/512.png',
  },
  {
    country: 'Bosnia and Herzegovina',
    alpha2: 'BA',
    alpha3: 'BIH',
    numeric: 70,
    latitude: 44,
    longitude: 18,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/ba/512.png',
  },
  {
    country: 'Bulgaria',
    alpha2: 'BG',
    alpha3: 'BGR',
    numeric: 100,
    latitude: 43,
    longitude: 25,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/bg/512.png',
  },
  {
    country: 'Croatia',
    alpha2: 'HR',
    alpha3: 'HRV',
    numeric: 191,
    latitude: 45.1667,
    longitude: 15.5,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/hr/512.png',
  },
  {
    country: 'Czech Republic',
    alpha2: 'CZ',
    alpha3: 'CZE',
    numeric: 203,
    latitude: 49.75,
    longitude: 15.5,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/cz/512.png',
  },
  {
    country: 'Denmark',
    alpha2: 'DK',
    alpha3: 'DNK',
    numeric: 208,
    latitude: 56,
    longitude: 10,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/dk/512.png',
  },
  {
    country: 'Estonia',
    alpha2: 'EE',
    alpha3: 'EST',
    numeric: 233,
    latitude: 59,
    longitude: 26,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/ee/512.png',
  },
  {
    country: 'Faroe Islands',
    alpha2: 'FO',
    alpha3: 'FRO',
    numeric: 234,
    latitude: 62,
    longitude: -7,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/fo/512.png',
  },
  {
    country: 'Finland',
    alpha2: 'FI',
    alpha3: 'FIN',
    numeric: 246,
    latitude: 64,
    longitude: 26,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/fi/512.png',
  },
  {
    country: 'France',
    alpha2: 'FR',
    alpha3: 'FRA',
    numeric: 250,
    latitude: 46,
    longitude: 2,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/fr/512.png',
  },
  {
    country: 'Germany',
    alpha2: 'DE',
    alpha3: 'DEU',
    numeric: 276,
    latitude: 51,
    longitude: 9,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/de/512.png',
  },
  {
    country: 'Gibraltar',
    alpha2: 'GI',
    alpha3: 'GIB',
    numeric: 292,
    latitude: 36.1833,
    longitude: -5.3667,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/gi/512.png',
  },
  {
    country: 'Greece',
    alpha2: 'GR',
    alpha3: 'GRC',
    numeric: 300,
    latitude: 39,
    longitude: 22,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/gr/512.png',
  },
  {
    country: 'Hungary',
    alpha2: 'HU',
    alpha3: 'HUN',
    numeric: 348,
    latitude: 47,
    longitude: 20,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/hu/512.png',
  },
  {
    country: 'Iceland',
    alpha2: 'IS',
    alpha3: 'ISL',
    numeric: 352,
    latitude: 65,
    longitude: -18,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/is/512.png',
  },
  {
    country: 'Ireland',
    alpha2: 'IE',
    alpha3: 'IRL',
    numeric: 372,
    latitude: 53,
    longitude: -8,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/ie/512.png',
  },
  {
    country: 'Isle of Man',
    alpha2: 'IM',
    alpha3: 'IMN',
    numeric: 833,
    latitude: 54.23,
    longitude: -4.55,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/im/512.png',
  },
  {
    country: 'Italy',
    alpha2: 'IT',
    alpha3: 'ITA',
    numeric: 380,
    latitude: 42.8333,
    longitude: 12.8333,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/it/512.png',
  },
  {
    country: 'Latvia',
    alpha2: 'LV',
    alpha3: 'LVA',
    numeric: 428,
    latitude: 57,
    longitude: 25,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/lv/512.png',
  },
  {
    country: 'Liechtenstein',
    alpha2: 'LI',
    alpha3: 'LIE',
    numeric: 438,
    latitude: 47.1667,
    longitude: 9.5333,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/li/512.png',
  },
  {
    country: 'Lithuania',
    alpha2: 'LT',
    alpha3: 'LTU',
    numeric: 440,
    latitude: 56,
    longitude: 24,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/lt/512.png',
  },
  {
    country: 'Luxembourg',
    alpha2: 'LU',
    alpha3: 'LUX',
    numeric: 442,
    latitude: 49.75,
    longitude: 6.1667,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/lu/512.png',
  },
  {
    country: 'Malta',
    alpha2: 'MT',
    alpha3: 'MLT',
    numeric: 470,
    latitude: 35.8333,
    longitude: 14.5833,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/mt/512.png',
  },
  {
    country: 'Monaco',
    alpha2: 'MC',
    alpha3: 'MCO',
    numeric: 492,
    latitude: 43.7333,
    longitude: 7.4,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/mc/512.png',
  },
  {
    country: 'Montenegro',
    alpha2: 'ME',
    alpha3: 'MNE',
    numeric: 499,
    latitude: 42,
    longitude: 19,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/me/512.png',
  },
  {
    country: 'Netherlands',
    alpha2: 'NL',
    alpha3: 'NLD',
    numeric: 528,
    latitude: 52.5,
    longitude: 5.75,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/nl/512.png',
  },
  {
    country: 'Norway',
    alpha2: 'NO',
    alpha3: 'NOR',
    numeric: 578,
    latitude: 62,
    longitude: 10,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/no/512.png',
  },
  {
    country: 'Poland',
    alpha2: 'PL',
    alpha3: 'POL',
    numeric: 616,
    latitude: 52,
    longitude: 20,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/pl/512.png',
  },
  {
    country: 'Portugal',
    alpha2: 'PT',
    alpha3: 'PRT',
    numeric: 620,
    latitude: 39.5,
    longitude: -8,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/pt/512.png',
  },
  {
    country: 'Romania',
    alpha2: 'RO',
    alpha3: 'ROU',
    numeric: 642,
    latitude: 46,
    longitude: 25,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/ro/512.png',
  },
  {
    country: 'Serbia',
    alpha2: 'RS',
    alpha3: 'SRB',
    numeric: 688,
    latitude: 44,
    longitude: 21,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/rs/512.png',
  },
  {
    country: 'Slovakia',
    alpha2: 'SK',
    alpha3: 'SVK',
    numeric: 703,
    latitude: 48.6667,
    longitude: 19.5,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/sk/512.png',
  },
  {
    country: 'Slovenia',
    alpha2: 'SI',
    alpha3: 'SVN',
    numeric: 705,
    latitude: 46,
    longitude: 15,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/si/512.png',
  },
  {
    country: 'Spain',
    alpha2: 'ES',
    alpha3: 'ESP',
    numeric: 724,
    latitude: 40,
    longitude: -4,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/es/512.png',
  },
  {
    country: 'Sweden',
    alpha2: 'SE',
    alpha3: 'SWE',
    numeric: 752,
    latitude: 62,
    longitude: 15,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/se/512.png',
  },
  {
    country: 'Switzerland',
    alpha2: 'CH',
    alpha3: 'CHE',
    numeric: 756,
    latitude: 47,
    longitude: 8,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/ch/512.png',
  },
  {
    country: 'Ukraine',
    alpha2: 'UA',
    alpha3: 'UKR',
    numeric: 804,
    latitude: 49,
    longitude: 32,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/ua/512.png',
  },
  {
    country: 'United Kingdom',
    alpha2: 'GB',
    alpha3: 'GBR',
    numeric: 826,
    latitude: 54,
    longitude: -2,
    continent: 'Europe',
    map: 'https://raw.githubusercontent.com/djaiss/mapsicon/master/europe/gb/512.png',
  },
];

export default countriesData;
